### ISSUE TITLE
Use encodeUriComponent when adding parameters to query parameters URL

### ISSUE THREAD

**Issue by philpott** [stormdigital/gtm-template-salesforce-audience-studio-event-pixel#7]
https://github.com/stormdigital/gtm-template-salesforce-audience-studio-event-pixel/blob/eda30d55a8dfcaf8308762174af6523f73f21013/template.tpl#L136

Please use encodeUriComponent when adding parameters to query parameters URL.

https://developers.google.com/tag-manager/templates/api#encodeuricomponent

**Comment by Pixeldenker** [comment]
Thanks for the heads up @philpott. This is fixed in the latest commit. Will appear on GTM within 2 to 3 days.
